name = "Daily Digest"

packages = ["sqlite3", "python-dateutil", "scikit-learn", "pandas"]

[files]
"/config.py" = "./config.py"
"/local_storage.py" = "./local_storage.py"
"/database/Database.py" = "./Database.py"
"/database/scraper_data.db" = "./scraper_data.db"
"/Article.py" = "./Article.py"
"/buttons.py" = "./buttons.py"